#!/bin/sh
cd $(dirname $0)

# VARIABLES
MAX_HEAP_MEM=$(echo "$AWS_LAMBDA_FUNCTION_MEMORY_SIZE \\* 60 / 100")
HEAP_MEM=${HEAP_MEM:-$(eval expr $MAX_HEAP_MEM)}
JAVA_OPTS=${JAVA_OPTS:- -Xmx${HEAP_MEM}m }

# MAIN
java ${JAVA_OPTS} -cp .:lib/* lambdify.core.AwsLambdaRuntime
